### PR TITLE
Creating Guessing Game

### LINKED ISSUE #11: Creating Guess Game
- [x] Creating `guessingGame.html`;
- [x] Creating `styleGuessing.css`;
- [x] Creating `guessing.js`;
- [x] Fixing all the functions;

### PR DESCRIPTION
**Pull request by abelRoland**
OMG! I made a PR in the HYF repo by mistake!

Now, hopefully I am doing all right.

This closes #11

### CODE REVIEW

**Comment by Feruzteame** [comment]
ja, even i made a mistake as well but normally i close the pull-request. 👍

**Review by Feruzteame — APPROVED** [review]

**Comment by aleks2407** [comment]
I had the same))))))saw yours there too and it made me feel a bit better))
thanks for good job!

**Review by aleks2407 — APPROVED** [review]
Nice! Thanks

**Review by yildiraykoyuncu — APPROVED** [review]
Well done

**Pull request merged**
